% Yukai Qian
% Duke Electric Vehicles
%
% Tract  Tractive force generated by the rear wheel.
%
%   F = Tract(V)
%
%   V       (m/s)   1-by-N vector of horizontal velocities.
%   F       (N)     1-by-N vector of tractive forces.
%
%   Considering acceleration, rolling resistance, air drag, cornering loss,
%   wheel drag and elevation change.

function F = Tract(V)

global track mu m mg rho cdA cCor c1 c2

% Time increments
dt = TimeIncr(V);

% Acceleration
a = Incr(V) ./ dt;
fAcc = m*a;

% Air drag
fAir = 1/2 * rho * cdA * V.^2;

% Rolling resistance
fRoll = mu*mg * ones(size(V));

% Cornering loss
omega = track.dyaw ./ dt;        % (rad/s) Angular velocity.
alpha = m*V.*abs(omega) ./ cCor; % (rad)   Tire slip angle.
fCor  = cCor .* alpha.^2;

% Wheel drag
fWheel = c1 * V.^2 + c2;

% Elevation change
fSlope = track.slope*mg;

% Tractive force
F = [fAcc; fAir; fRoll; fCor; fWheel; fSlope];