% Yukai Qian
% Duke Electric Vehicles

function F = Traction(M, V, OMEGA, SLOPE, T)
% Traction  Tractive force generated by the rear wheel.
%
%   F = Traction(V, OMEGA, VZ)
%
%   M       (kg) Mass.
%   V       (m/s) Horizontal speed.
%   OMEGA   (rad/s) Cornering angular velocity.
%   SLOPE   Slope of track.
%   T       (s) Time.
%   F       (N) Traction.
%
%   Considering acceleration, rolling resistance, air drag, cornering loss
%   and elevation change.

MU  = 0.005; % Rolling resistance coefficient.
G   = 9.809; % (m/s^2) Local gravitational acceleration.
RHO = 1.2;   % (kg/m^3) Air density at 20 C.
CDA = 0.4;   % (m^2) Drag coefficient times area.
COR = 

% Acceleration
A = gradient(V)./gradient(T);
FACC = M*A;

% Rolling resistance
FROLL = MU*M*G;

% Air drag
FAIR = 1/2 * RHO * CDA * V.^2;

% Cornering loss


% Elevation change
FSLOPE = SLOPE*M*G;